# fly.toml app configuration file generated for yarg-introducer on 2026-01-01T15:59:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yarg-introducer'
primary_region = 'iad'

[build]
  dockerfile = 'src/YARG.Introducer/Dockerfile'

[env]
  ASPNETCORE_URLS = 'http://+:8080'
  PUNCH_PORT = '9051'
  RELAY_PORT = '9052'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = 'udp'
  internal_port = 9051

  [[services.ports]]
    port = 9051

[[services]]
  protocol = 'udp'
  internal_port = 9052

  [[services.ports]]
    port = 9052

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '10s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
